version: '2'
services:
  mongoangularspringbootapp-mongodb:
    image: mongo:4.0.9
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/mongoAngularSpringBootApp/mongodb/:/data/db/
